osx_image: xcode8
language: objective-c
notifications:
  email: false
before_install:
- gem install bundler
- bundle install
script:
- bundle exec fastlane build_XXXXX
- bundle exec fastlane test_XXXXX