desc "Builds XXXXX for all the platforms"
lane :build_XXXXX do
  xcodebuild(workspace: "XXXXX.xcworkspace", scheme: "XXXXX", destination: "platform=iOS Simulator,OS=10.0,name=iPhone 6", configuration: "Debug", build_settings: {"ONLY_ACTIVE_ARCH" => "NO", "CODE_SIGNING_REQUIRED" => "NO", "CODE_SIGN_IDENTITY" => "" } )
  xcodebuild(workspace: "XXXXX.xcworkspace", scheme: "XXXXX", destination: "platform=OS X,arch=x86_64", configuration: "Debug", build_settings: {"ONLY_ACTIVE_ARCH" => "NO", "CODE_SIGNING_REQUIRED" => "NO", "CODE_SIGN_IDENTITY" => "" } )
  xcodebuild(workspace: "XXXXX.xcworkspace", scheme: "XXXXX", destination: "platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p", configuration: "Debug", build_settings: {"ONLY_ACTIVE_ARCH" => "NO", "CODE_SIGNING_REQUIRED" => "NO", "CODE_SIGN_IDENTITY" => "" } )
  xcodebuild(workspace: "XXXXX.xcworkspace", scheme: "XXXXX", destination: "OS=3.0,name=Apple Watch Series 2 - 38mm watchOS 3.0", configuration: "Debug", build_settings: {"ONLY_ACTIVE_ARCH" => "NO", "CODE_SIGNING_REQUIRED" => "NO", "CODE_SIGN_IDENTITY" => "" } )
end

desc "Runs all XXXXX tests"
lane :test_XXXXX do
  scan(workspace: "XXXXX.xcworkspace", scheme: "XXXXX")
end